// GLSL Vertex Shader "VS"
// Generated by XShaderCompiler
// 14/08/2019 22:56:44

#version 450

layout(location = 0) in vec3 position;
layout(location = 1) in vec2 texCoord;

layout(location = 0) out vec2 xsv_TEXCOORD0;

layout(std140, row_major, binding = 0) uniform Matrices
{
    mat4 wvpMatrix;
};

void main()
{
    gl_Position = (vec4(position, 1) * wvpMatrix);
    xsv_TEXCOORD0 = texCoord;
}

