/*
 * D3D12Builtin.h
 * 
 * This file is part of the "LLGL" project (Copyright (c) 2015-2018 by Lukas Hermanns)
 * See "LICENSE.txt" for license information.
 */

#ifndef LLGL_D3D12_BUILTIN_H
#define LLGL_D3D12_BUILTIN_H


#define LLGL_IDR_GENERATEMIPS1D_CS              101
#define LLGL_IDR_GENERATEMIPS1D_CS_ODDX         102
#define LLGL_IDR_GENERATEMIPS1D_CS_SRGB         103
#define LLGL_IDR_GENERATEMIPS1D_CS_SRGB_ODDX    104

#define LLGL_IDR_GENERATEMIPS2D_CS              105
#define LLGL_IDR_GENERATEMIPS2D_CS_ODDX         106
#define LLGL_IDR_GENERATEMIPS2D_CS_ODDY         107
#define LLGL_IDR_GENERATEMIPS2D_CS_ODDXY        108
#define LLGL_IDR_GENERATEMIPS2D_CS_SRGB         109
#define LLGL_IDR_GENERATEMIPS2D_CS_SRGB_ODDX    110
#define LLGL_IDR_GENERATEMIPS2D_CS_SRGB_ODDY    111
#define LLGL_IDR_GENERATEMIPS2D_CS_SRGB_ODDXY   112

#define LLGL_IDR_GENERATEMIPS3D_CS              113
#define LLGL_IDR_GENERATEMIPS3D_CS_ODDX         114
#define LLGL_IDR_GENERATEMIPS3D_CS_ODDY         115
#define LLGL_IDR_GENERATEMIPS3D_CS_ODDZ         116
#define LLGL_IDR_GENERATEMIPS3D_CS_ODDXY        117
#define LLGL_IDR_GENERATEMIPS3D_CS_ODDYZ        118
#define LLGL_IDR_GENERATEMIPS3D_CS_ODDXZ        119
#define LLGL_IDR_GENERATEMIPS3D_CS_ODDXYZ       120
#define LLGL_IDR_GENERATEMIPS3D_CS_SRGB         121
#define LLGL_IDR_GENERATEMIPS3D_CS_SRGB_ODDX    122
#define LLGL_IDR_GENERATEMIPS3D_CS_SRGB_ODDY    123
#define LLGL_IDR_GENERATEMIPS3D_CS_SRGB_ODDZ    124
#define LLGL_IDR_GENERATEMIPS3D_CS_SRGB_ODDXY   125
#define LLGL_IDR_GENERATEMIPS3D_CS_SRGB_ODDYZ   126
#define LLGL_IDR_GENERATEMIPS3D_CS_SRGB_ODDXZ   127
#define LLGL_IDR_GENERATEMIPS3D_CS_SRGB_ODDXYZ  128


#endif



// ================================================================================
