/*
 * D3D12Builtin.h
 * 
 * This file is part of the "LLGL" project (Copyright (c) 2015-2019 by Lukas Hermanns)
 * See "LICENSE.txt" for license information.
 */

#ifndef LLGL_D3D12_BUILTIN_H
#define LLGL_D3D12_BUILTIN_H


#define LLGL_IDR_GENERATEMIPS1D_CS              1201
#define LLGL_IDR_GENERATEMIPS1D_CS_ODDX         1202
#define LLGL_IDR_GENERATEMIPS1D_CS_SRGB         1203
#define LLGL_IDR_GENERATEMIPS1D_CS_SRGB_ODDX    1204

#define LLGL_IDR_GENERATEMIPS2D_CS              1205
#define LLGL_IDR_GENERATEMIPS2D_CS_ODDX         1206
#define LLGL_IDR_GENERATEMIPS2D_CS_ODDY         1207
#define LLGL_IDR_GENERATEMIPS2D_CS_ODDXY        1208
#define LLGL_IDR_GENERATEMIPS2D_CS_SRGB         1209
#define LLGL_IDR_GENERATEMIPS2D_CS_SRGB_ODDX    1210
#define LLGL_IDR_GENERATEMIPS2D_CS_SRGB_ODDY    1211
#define LLGL_IDR_GENERATEMIPS2D_CS_SRGB_ODDXY   1212

#define LLGL_IDR_GENERATEMIPS3D_CS              1213
#define LLGL_IDR_GENERATEMIPS3D_CS_ODDX         1214
#define LLGL_IDR_GENERATEMIPS3D_CS_ODDY         1215
#define LLGL_IDR_GENERATEMIPS3D_CS_ODDXY        1216
#define LLGL_IDR_GENERATEMIPS3D_CS_ODDZ         1217
#define LLGL_IDR_GENERATEMIPS3D_CS_ODDXZ        1218
#define LLGL_IDR_GENERATEMIPS3D_CS_ODDYZ        1219
#define LLGL_IDR_GENERATEMIPS3D_CS_ODDXYZ       1220
#define LLGL_IDR_GENERATEMIPS3D_CS_SRGB         1221
#define LLGL_IDR_GENERATEMIPS3D_CS_SRGB_ODDX    1222
#define LLGL_IDR_GENERATEMIPS3D_CS_SRGB_ODDY    1223
#define LLGL_IDR_GENERATEMIPS3D_CS_SRGB_ODDXY   1224
#define LLGL_IDR_GENERATEMIPS3D_CS_SRGB_ODDZ    1225
#define LLGL_IDR_GENERATEMIPS3D_CS_SRGB_ODDXZ   1226
#define LLGL_IDR_GENERATEMIPS3D_CS_SRGB_ODDYZ   1227
#define LLGL_IDR_GENERATEMIPS3D_CS_SRGB_ODDXYZ  1228


#endif



// ================================================================================
