/*
 * D3D9StateManager.h
 *
 * Copyright (c) 2015 Lukas Hermanns. All rights reserved.
 * Licensed under the terms of the BSD 3-Clause license (see LICENSE.txt).
 */

#ifndef LLGL_D3D9_STATE_MANAGER_H
#define LLGL_D3D9_STATE_MANAGER_H


#include "D3D9State.h"
#include "../Direct3D9.h"
#include "../Buffer/D3D9AutoGeneratedIndexBuffer.h"
#include "../../DXCommon/ComPtr.h"


namespace LLGL
{


struct D3D9SamplerState;
struct D3D9StreamSourceFreq;
class D3D9EmulatedSampler;
class D3D9DepthStencilState;
class D3D9RasterizerState;
class D3D9BlendState;

class D3D9StateManager
{

    public:

        D3D9StateManager(IDirect3DDevice9* device);

        inline IDirect3DDevice9* GetDevice() const
        {
            return device_.Get();
        }

        void SetRenderState(D3DRENDERSTATETYPE state, DWORD value);
        void SetTextureStageState(DWORD stage, D3DTEXTURESTAGESTATETYPE type, DWORD value);
        void SetSamplerState(DWORD stage, D3DSAMPLERSTATETYPE type, DWORD value);
        void SetSamplerState(DWORD stage, const D3D9SamplerState& d3dState);

        void BindTexture(DWORD stage, IDirect3DBaseTexture9* texture);
        void BindSampler(DWORD stage, const D3D9EmulatedSampler* sampler);

        void BindDepthStencilState(D3D9DepthStencilState* depthStencilState);
        void BindRasterizerState(D3D9RasterizerState* rasterizerState);
        void BindBlendState(D3D9BlendState* blendState);

        void SetRenderTargets(UINT numColorTargets, IDirect3DSurface9* const * renderTargets, IDirect3DSurface9* depthStencil);
        void Clear(DWORD flags, D3DCOLOR color, float z, DWORD stencil);

        void SetStreamSource(UINT stream, const D3DStreamSource& source);
        void SetStreamSourceFreqIndexData(UINT numInstances);
        void SetStreamSourceFreqInstanceData(UINT count, const D3D9StreamSourceFreq* streamSourceFreq);

        void SetInstanceOffset(UINT firstInstance);

        void SetIndices(IDirect3DIndexBuffer9* indexBuffer);
        void SetAutoIndices(UINT numIndices);

    private:

        static constexpr UINT maxNumStreams = 16;

        struct D3DStreamSourceFreq
        {
            UINT dividers[maxNumStreams]    = {};
            UINT streamUpperBound           = 0;
        };

        struct D3DInputAssembly
        {
            IDirect3DIndexBuffer9*  indexBuffer                     = nullptr;
            D3DStreamSource         streamSource[maxNumStreams]     = {};
            D3DStreamSourceFreq     streamSourceFreq;
            UINT                    streamSourceOffsetUpperBound    = 0; // Upper bound stream source with an offset
        };

        struct D3DTextureStage
        {
            static constexpr DWORD numTextureStageStates = static_cast<DWORD>(D3DTSS_CONSTANT);
            static_assert(numTextureStageStates == 32, "D3DRS_BLENDOPALPHA is expected to be equal to 32");
            DWORD stageStates[numTextureStageStates] = {};

            static constexpr DWORD numSamplerStates = static_cast<DWORD>(D3DSAMP_DMAPOFFSET);
            static_assert(numSamplerStates == 13, "D3DSAMP_DMAPOFFSET is expected to be equal to 13");
            DWORD samplerStates[numSamplerStates] = {};

            IDirect3DBaseTexture9*      boundD3DBaseTexture = nullptr;
            const D3D9EmulatedSampler*  boundSampler        = nullptr;
        };

    private:

        void SetSamplerStateInternal(DWORD stage, D3DSAMPLERSTATETYPE type, DWORD value);
        void SetStreamSourceFreqInternal(UINT stream, UINT divider);

        void InitializeForFixedFunctionPipeline();

    private:

        static constexpr DWORD numTextureStages = 8;

        static constexpr DWORD numRenderStates = static_cast<DWORD>(D3DRS_BLENDOPALPHA);
        static_assert(numRenderStates == 209, "D3DRS_BLENDOPALPHA is expected to be equal to 209");

        ComPtr<IDirect3DDevice9>        device_;

        D3DInputAssembly                inputAssembly_;
        DWORD                           renderStates_[numRenderStates]      = {};
        D3DTextureStage                 textureStages_[numTextureStages];
        UINT                            numColorTargets_                    = 0;
        DWORD                           clearMask_                          = 0; // Bitmask of render targets that can be cleared

        D3D9AutoGeneratedIndexBuffer    autoGenIndexBuffer16_;
        D3D9AutoGeneratedIndexBuffer    autoGenIndexBuffer32_;

        D3D9DepthStencilState*          boundDepthStencilState_             = nullptr;
        D3D9RasterizerState*            boundRasterizerState_               = nullptr;
        D3D9BlendState*                 boundBlendState_                    = nullptr;

};


} // /namespace LLGL


#endif



// ================================================================================
