/*
 * ResourceBinding.450core.comp
 *
 * Copyright (c) 2015 Lukas Hermanns. All rights reserved.
 * Licensed under the terms of the BSD 3-Clause license (see LICENSE.txt).
 */

#version 450 core

#ifndef ENABLE_SPIRV
#define ENABLE_SPIRV 0
#endif

#if ENABLE_SPIRV
#extension  GL_EXT_samplerless_texture_functions : enable
#endif

layout(binding = 0, std430) readonly buffer inBufferA
{
    ivec4 inBufferA_arr[];
};
layout(binding = 1, std430) readonly buffer inBufferB
{
    ivec4 inBufferB_arr[];
};
layout(binding = 2, std430) writeonly buffer outBufferA
{
    ivec4 outBufferA_arr[];
};
layout(binding = 4, std430) writeonly buffer outBufferB
{
    ivec4 outBufferB_arr[];
};

#if ENABLE_SPIRV
layout(binding = 5) uniform itexture1D inTextureA;
layout(binding = 6) uniform itexture1D inTextureB;
layout(binding = 7, rgba32i) uniform iimage1D outTextureA;
layout(binding = 8, rgba32i) uniform iimage1D outTextureB;
#else
layout(binding = 2) uniform isampler1D inTextureA;
layout(binding = 4) uniform isampler1D inTextureB;
layout(binding = 0, rgba32i) uniform iimage1D outTextureA;
layout(binding = 1, rgba32i) uniform iimage1D outTextureB;
#endif

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

void main()
{
    int id = int(gl_GlobalInvocationID.x);

    outBufferA_arr[id] = inBufferA_arr[id] + inBufferB_arr[id];
    outBufferB_arr[id] = (inBufferA_arr[id] - inBufferB_arr[id]) * 2;

    imageStore(outTextureA, id, (texelFetch(inTextureA, id, 0) + texelFetch(inTextureB, id, 0)));
    imageStore(outTextureB, id, (texelFetch(inTextureA, id, 0) - texelFetch(inTextureB, id, 0)) * 2);
}
