/*
 * QueryHeapFlags.h
 * 
 * This file is part of the "LLGL" project (Copyright (c) 2015-2018 by Lukas Hermanns)
 * See "LICENSE.txt" for license information.
 */

#ifndef LLGL_QUERY_HEAP_FLAGS_H
#define LLGL_QUERY_HEAP_FLAGS_H


#include "Constants.h"
#include <cstdint>


namespace LLGL
{


/* ----- Enumerations ----- */

/**
\brief Query type enumeration.
\see QueryHeapDescriptor::type
*/
enum class QueryType
{
    //! Number of samples that passed the depth test. This can be used as render condition.
    SamplesPassed,

    //! Non-zero if any samples passed the depth test. This can be used as render condition.
    AnySamplesPassed,

    //! Non-zero if any samples passed the depth test within a conservative rasterization. This can be used as render condition.
    AnySamplesPassedConservative,

    //! Elapsed time (in nanoseconds) between the begin- and end query command.
    TimeElapsed,

    //! Number of vertices that have been written into a stream output (also called "Transform Feedback").
    StreamOutPrimitivesWritten,

    //! Non-zero if any of the streaming output buffers (also called "Transform Feedback Buffers") has an overflow.
    StreamOutOverflow,

    /**
    \brief Pipeline statistics such as number of shader invocations, generated primitives, etc.
    \see QueryPipelineStatistics
    */
    PipelineStatistics,
};


/* ----- Structures ----- */

/**
\brief Query data structure for pipeline statistics.
\remarks If the renderer does not support individual members of this structure, they will be set to QueryPipelineStatistics::invalidNum.
\see QueryType::PipelineStatistics
\see CommandQueue::QueryPipelineStatisticsResult
*/
struct QueryPipelineStatistics
{
    #if 1//TODO: remove this
    //! Number of generated primitives which are send to the rasterizer (either emitted from the geometry or vertex shader).
    std::uint64_t numPrimitivesGenerated                = 0;
    #endif

    //! Number of vertices submitted to the input-assembly.
    std::uint64_t numVerticesSubmitted                  = 0;

    //! Number of primitives submitted to the input-assembly.
    std::uint64_t numPrimitivesSubmitted                = 0;

    //! Number of vertex shader invocations.
    std::uint64_t numVertexShaderInvocations            = 0;

    //! Number of tessellation-control shader invocations.
    std::uint64_t numTessControlShaderInvocations       = 0;

    //! Number of tessellation-evaluation shader invocations.
    std::uint64_t numTessEvaluationShaderInvocations    = 0;

    //! Number of geometry shader invocations.
    std::uint64_t numGeometryShaderInvocations          = 0;

    //! Number of fragment shader invocations.
    std::uint64_t numFragmentShaderInvocations          = 0;

    //! Number of compute shader invocations.
    std::uint64_t numComputeShaderInvocations           = 0;

    //! Number of primitives generated by the geometry shader.
    std::uint64_t numGeometryPrimitivesGenerated        = 0;

    //! Number of primitives that reached the primitive clipping stage.
    std::uint64_t numClippingInputPrimitives            = 0;

    //! Number of primitives that passed the primitive clipping stage.
    std::uint64_t numClippingOutputPrimitives           = 0;
};

/**
\brief Query heap descriptor structure.
\see RenderSystem::CreateQueryHeap
*/
struct QueryHeapDescriptor
{
    //! Specifies the type of queries in the heap. By default QueryType::SamplesPassed.
    QueryType       type            = QueryType::SamplesPassed;

    //! Specifies the number of queries in the heap. This must be greater than zero. By default 1.
    std::uint32_t   numQueries      = 1;

    /**
    \brief Specifies whether the queries are to be used as render conditions. By default false.
    \remarks If this is true, the results of the queries cannot be retrieved by CommandBuffer::QueryResult and the member \c type can only have one of the following values:
    - QueryType::SamplesPassed
    - QueryType::AnySamplesPassed
    - QueryType::AnySamplesPassedConservative
    - QueryType::StreamOutOverflow
    \remarks Render conditions can be used to render complex geometry under the condition that
    a previous (commonly significantly smaller) geometry has passed the depth and stencil tests.
    \see CommandBuffer::BeginRenderCondition
    \see CommandBuffer::EndRenderCondition
    \note Only supported with: OpenGL, Direct3D 11, Direct3D 12.
    */
    bool            renderCondition = false;
};


} // /namespace LLGL


#endif



// ================================================================================
