/*
 * D3D9AutoGeneratedIndexBuffer.h
 *
 * Copyright (c) 2015 Lukas Hermanns. All rights reserved.
 * Licensed under the terms of the BSD 3-Clause license (see LICENSE.txt).
 */

#ifndef LLGL_D3D9_AUTO_GENERATED_INDEX_BUFFER_H
#define LLGL_D3D9_AUTO_GENERATED_INDEX_BUFFER_H


#include "../Direct3D9.h"
#include "../../DXCommon/ComPtr.h"


namespace LLGL
{


class D3D9AutoGeneratedIndexBuffer
{

    public:

        D3D9AutoGeneratedIndexBuffer(D3DFORMAT format);

        IDirect3DIndexBuffer9* GetNativeForMaxIndex(IDirect3DDevice9* device, UINT numIndices);

    private:

        bool ResizeBuffer(IDirect3DDevice9* device, UINT numIndices);

    private:

        ComPtr<IDirect3DIndexBuffer9>   d3dBuffer_;
        D3DFORMAT                       format_     = D3DFMT_INDEX16;
        UINT                            numIndices_ = 0;

};


} // /namespace LLGL


#endif



// ================================================================================
