/*
 * D3D9AutoGeneratedIndexBuffer.cpp
 *
 * Copyright (c) 2015 Lukas Hermanns. All rights reserved.
 * Licensed under the terms of the BSD 3-Clause license (see LICENSE.txt).
 */

#include "D3D9AutoGeneratedIndexBuffer.h"
#include "../../../Core/CoreUtils.h"
#include "../D3D9Core.h"
#include <LLGL/Utils/ForRange.h>
#include <limits.h>
#include <algorithm>


namespace LLGL
{


static UINT GetIndexLimitForD3DFormat(D3DFORMAT format)
{
    switch (format)
    {
        case D3DFMT_INDEX16:    return UINT16_MAX;
        case D3DFMT_INDEX32:    return UINT32_MAX;
        default:                return 0;
    }
}

static UINT GetElementSizeForD3DFormat(D3DFORMAT format)
{
    switch (format)
    {
        case D3DFMT_INDEX16:    return 1;
        case D3DFMT_INDEX32:    return 2;
        default:                return 0;
    }
}

D3D9AutoGeneratedIndexBuffer::D3D9AutoGeneratedIndexBuffer(D3DFORMAT format) :
    format_ { format }
{
}

IDirect3DIndexBuffer9* D3D9AutoGeneratedIndexBuffer::GetNativeForMaxIndex(IDirect3DDevice9* device, UINT numIndices)
{
    if (numIndices > numIndices_ && !ResizeBuffer(device, numIndices))
        return nullptr;
    return d3dBuffer_.Get();
}


/*
 * ======= Private: =======
 */

template <typename T>
void AutoGeneratedIndices(void* dst, UINT count)
{
    T* dstIndices = static_cast<T*>(dst);
    for_range(i, count)
        dstIndices[i] = static_cast<T>(i);
}

bool D3D9AutoGeneratedIndexBuffer::ResizeBuffer(IDirect3DDevice9* device, UINT numIndices)
{
    /* Determine new index buffer capacity */
    const UINT numIndicesLimit = GetIndexLimitForD3DFormat(format_);
    if (numIndices > numIndicesLimit)
        return false;

    numIndices_ = std::min<UINT>(numIndicesLimit, numIndices + numIndices/2);
    const UINT bufferLength = numIndices_ * GetElementSizeForD3DFormat(format_);

    /* Create new index buffer */
    HRESULT hr = device->CreateIndexBuffer(
        bufferLength,
        D3DUSAGE_WRITEONLY, // Usage
        format_,
        D3DPOOL_DEFAULT,
        d3dBuffer_.ReleaseAndGetAddressOf(),
        nullptr // Shared handle (must be null)
    );
    D3DThrowIfCreateFailed(hr, "IDirect3DIndexBuffer9");

    /* Fill buffer with auto-generated sequential index data */
    void* lockedData = nullptr;
    hr = d3dBuffer_->Lock(0, bufferLength, &lockedData, D3DLOCK_DISCARD);
    D3DThrowIfFailed(hr, "failed to lock auto-generated D3D9 index buffer");

    LLGL_ASSERT_PTR(lockedData);
    switch (format_)
    {
        case D3DFMT_INDEX16:
            AutoGeneratedIndices<std::uint16_t>(lockedData, numIndices_);
            break;
        case D3DFMT_INDEX32:
            AutoGeneratedIndices<std::uint32_t>(lockedData, numIndices_);
            break;
    }

    hr = d3dBuffer_->Unlock();
    D3DThrowIfFailed(hr, "failed to unlock auto-generated D3D9 index buffer");

    return true;
}


} // /namespace LLGL



// ================================================================================
