// GLSL Vertex Shader "VScene"
// Generated by XShaderCompiler
// 19/08/2019 20:23:04

#version 140

in vec3 position;
in vec3 normal;

out vec4 xsv_NDC0;
out vec4 xsv_WORLDPOS0;
out vec4 xsv_MODELPOS0;
out vec4 xsv_NORMAL0;

layout(std140, row_major) uniform Settings
{
    mat4  wMatrix;
    mat4  wMatrixInv;
    mat4  vpMatrix;
    mat4  vpMatrixInv;
    vec3  lightDir;
    float shininess;
    vec3  viewPos;
    float threshold;
    vec3  albedo;
    float reflectance;
};

void main()
{
    xsv_MODELPOS0 = vec4(position, 1);
    xsv_WORLDPOS0 = (xsv_MODELPOS0 * wMatrix);
    gl_Position = (xsv_WORLDPOS0 * vpMatrix);
    xsv_NDC0 = gl_Position / gl_Position.w;
    xsv_NORMAL0 = (vec4(normal, 0) * wMatrix);
}

