// GLSL compute shader
#version 450 core
#extension GL_EXT_samplerless_texture_functions : enable

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(binding = 0) uniform texture2D tex;
layout(binding = 1) writeonly uniform image2D texOut;

void main()
{
    ivec2 gridPos = ivec2(gl_GlobalInvocationID.xy);
    vec2 tc = vec2(gridPos) * 0.1;
    imageStore(texOut, gridPos, texelFetch(tex, gridPos, 0) * (sin(tc.x)*0.2 + 1.0));
}
