# Find Metal
#
# METALKIT_INCLUDE_DIR
# METALKIT_LIBRARY
# METALKIT_LIBRARY_DIR
# METALKIT_FOUND

if(APPLE)
	find_path(METALKIT_INCLUDE_DIR NAMES metalkit/metalkit.h PATHS ${CMAKE_FIND_ROOT_PATH})
	find_library(METALKIT_LIBRARY NAMES metalkit PATHS ${CMAKE_FIND_ROOT_PATH})
	get_filename_component(METALKIT_LIBRARY_DIR ${METALKIT_LIBRARY} DIRECTORY)

	include(FindPackageHandleStandardArgs)
	FIND_PACKAGE_HANDLE_STANDARD_ARGS(MetalKit DEFAULT_MSG METALKIT_LIBRARY METALKIT_INCLUDE_DIR)

	mark_as_advanced(METALKIT_INCLUDE_DIR METALKIT_LIBRARY)
endif()

