# Find Metal
#
# METAL_INCLUDE_DIR
# METAL_LIBRARY
# METAL_LIBRARY_DIR
# METAL_FOUND

if(APPLE)
	find_path(METAL_INCLUDE_DIR NAMES metal/metal.h PATHS ${CMAKE_FIND_ROOT_PATH})
	find_library(METAL_LIBRARY NAMES metal PATHS ${CMAKE_FIND_ROOT_PATH})
	get_filename_component(METAL_LIBRARY_DIR ${METAL_LIBRARY} DIRECTORY)

	include(FindPackageHandleStandardArgs)
	FIND_PACKAGE_HANDLE_STANDARD_ARGS(Metal DEFAULT_MSG METAL_LIBRARY METAL_INCLUDE_DIR)

	mark_as_advanced(METAL_INCLUDE_DIR METAL_LIBRARY)
endif()

