// GLSL Fragment Shader "PS"
// Generated by XShaderCompiler
// 28/12/2016 12:38:44

#version 150

out vec4 SV_Target0;

in OutputVS
{
    vec2 texCoord;
}
inp;

uniform sampler2D colorMap;

void main()
{
    vec4 color = texture(colorMap, inp.texCoord);
    SV_Target0 = mix(vec4(1), color, color.a);
}

